import pandas as pd
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity
import numpy as np

## Implement similarity score to show the user.
## Plan to implement SQLite for .csv and Redis for caching later.

def load_ticket_data(resolved_tickets):
    df = pd.read_csv(resolved_tickets)
    if 'Subject' not in df.columns or 'Resolution' not in df.columns:
        raise ValueError("CSV file must contain 'Subject' and 'Resolution' columns.")
    return df

def vectorize_subjects(df):
    vectorizer = TfidfVectorizer()
    tfidf_matrix = vectorizer.fit_transform(df['Subject'])
    return tfidf_matrix, vectorizer

def vectorize_resolutions(df):
    vectorizer = TfidfVectorizer()
    tfidf_matrix = vectorizer.fit_transform(df['Resolution'])
    return tfidf_matrix, vectorizer

def find_similar_ticket(new_subject, tfidf_matrix, df, vectorizer):
    # Vectorize the new subject
    new_tfidf = vectorizer.transform([new_subject])
    
    # Calculate cosine similarities between the new subject and past ticket subjects
    cosine_similarities = cosine_similarity(new_tfidf, tfidf_matrix).flatten()
    
    # Find the index of the most similar ticket
    most_similar_idx = np.argmax(cosine_similarities)
    
    # Retrieve the most similar ticket's subject and resolution
    most_similar_ticket = df.iloc[most_similar_idx]
    
    return most_similar_ticket['Subject'], most_similar_ticket['Resolution']

def compare_ai_response_to_resolution(ai_response, resolution, df):
    # Vectorize the AI response and the resolution from the most similar ticket
    vectorizer = TfidfVectorizer()
    tfidf_matrix = vectorizer.fit_transform([resolution, ai_response])
    
    # Calculate cosine similarity between the AI response and the past resolution
    cosine_similarities = cosine_similarity(tfidf_matrix[0:1], tfidf_matrix[1:2]).flatten()
    
    # Calculate the similarity score (out of 100)
    similarity_score = cosine_similarities[0] * 100
    
    return similarity_score

if __name__ == "__main__":
    # Load the ticket data from a CSV file
    df = load_ticket_data('resolved_tickets.csv')

    # Vectorize the subjects
    tfidf_matrix, vectorizer = vectorize_subjects(df)

    # Input: new subject (could be scraped or passed dynamically)
    new_subject = "Campus Groups Profile Access"

    # Step 1: Find the most similar ticket based on the subject
    subject, resolution = find_similar_ticket(new_subject, tfidf_matrix, df, vectorizer)
    print(f"Most Similar Ticket Subject: {subject}\nResolution: {resolution}")

    # Example AI response (in practice, this would be generated by your AI model)
    ai_response = "Ensure that you have the necessary permissions to access the profile. Contact admin if access is denied."

    # Step 2: Compare the AI response to the most similar past resolution
    similarity_score = compare_ai_response_to_resolution(ai_response, resolution, df)
    print(f"AI Response Similarity Score: {similarity_score:.2f}%")
